name: pot
description: An easy and safe DI (Dependency Injection) solution for Dart with support for scoping.
version: 0.4.1
repository: https://github.com/kaboc/pot

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.4
