name: pot
description: An easy and safe DI (Dependency Injection) solution for Dart with support for scoping.
version: 0.3.1
homepage: https://github.com/kaboc/pot

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1
